spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    defer-datasource-initialization: true
  docker:
    username: nikodem
    password: zaq1
    host: 127.0.0.1
    sshPort: 422
    dockerPort: 2375
    sessionTimeout: 60000
    channelTimeout: 60000
    pathFile: /home/tests
    nameImage: docker-tester
    prefixContainer: solution_