spring:
#  datasource:
#    url: jdbc:h2:mem:test
#    username: sa
#    password:
#    driverClassName: org.h2.Driver
  datasource:
    url: jdbc:postgresql://localhost:5432/dpdb
    username: postgres
    password: zaq1

  jpa:
    show-sql: true
#    true jeśli H2 bedzie korzystane
    defer-datasource-initialization: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: none

  sql:
    init:
      mode: always
      platform: postgres
  liquibase:
    change-log: classpath:db/master.xml

  docker:
    username: nikodem
    password: zaq1
    host: 127.0.0.1
    sshPort: 422
    dockerPort: 2375
    sessionTimeout: 60000
    channelTimeout: 60000
    pathFile: /home/tests
    nameImage: docker-tester
    prefixContainer: solution_
